app:
  name: 'auction-go'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'auction-go'

postgres:
  pool_max: 2
  pg_url: 'postgres://elotro@localhost/auctiongo_dev'